apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: personal-website
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: website=harbor.schwartzdaniel.de/private/personal-website:dev
    argocd-image-updater.argoproj.io/portfolio.allow-tags: |
      regexp:.*
    argocd-image-updater.argoproj.io/portfolio.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/portfolio.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/portfolio.update-strategy: digest
    argocd-image-updater.argoproj.io/pull-policy: Always

spec:
  project: default
  source:
    repoURL: https://github.com/DanielSchwartz1/personal-website.git
    targetRevision: HEAD
    path: helm-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true